---
/**/controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 125 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    agro_base_controller:
      type: diff_drive_controller/DiffDriveController


gz_ros_control:
  ros__parameters:
    hold_joints: false
    position_proportional_gain: 0.5
    use_sim_time: true

/**/agro_base_controller:
  ros__parameters:
    use_sim_time: true

    # wheels
    left_wheel_names: [front_left_joint, near_left_joint]
    right_wheel_names: [front_right_joint, near_right_joint]

    # geometrics properties
    wheel_separation: 0.5015 #0.5015 0.440
    wheel_radius: 0.0615

    wheel_separation_multiplier: 1.45
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    tf_frame_prefix_enable: false
    
    odom_frame_id: odom
    base_frame_id: base_link

    pose_covariance_diagonal: [0.001, 0.001, 0.000, 0.000, 0.000, 0.05]
    twist_covariance_diagonal: [3.3e-5, 3.3e-5, 0.0, 0.0, 0.0, 2.8e-3] # estos valores salen experimentalmente

    open_loop: false
    position_feedback: true
    enable_odom_tf: false #false o true

    cmd_vel_timeout: 0.5 
    publish_limited_velocity: true

    velocity_rolling_window_size: 10

    # Frecuencia de publicacion de la odometría  los TF
    publish_rate: 50.0  


    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    # Limits from manual https://husarion.com/manuals/rosbot-xl/#hardware-guide
    linear:
      x:
        has_velocity_limits: true
        has_acceleration_limits: true
        has_jerk_limits: false
        # top speed is around 1.2m/s
        max_velocity: 0.8 # m/s
        # min_velocity -  When unspecified, -max_velocity is used
        max_acceleration: 1.0 # m/s^2
        # min_acceleration - When unspecified, -max_acceleration is used.
        max_jerk: 0.0 # m/s^3

    angular:
      z:
        has_velocity_limits: true
        has_acceleration_limits: true
        has_jerk_limits: false
        max_velocity: 3.14 # rad/s
        # min_velocity -  When unspecified, -max_velocity is used
        max_acceleration: 4.0 # rad/s^2
        # min_acceleration - When unspecified, -max_acceleration is used.
        max_jerk: 0.0 # rad/s^3